#!/usr/bin/env bash
# fetch-fonts.sh — (re)download the bundled editor fonts from Google Fonts and
# regenerate the @font-face stylesheet.
#
# For every family in the FONTS list it downloads the latin-subset .woff2 for
# weights 400 (normal) and 700 (bold) into frontend/src/assets/fonts/<id>-<w>.woff2,
# then writes frontend/src/theme/fonts.css with one @font-face block per file.
# These files are committed to the repo and wired up in:
#   - frontend/src/theme/fonts.css     (generated here; imported by main.ts)
#   - frontend/src/store.ts            (FONT_FAMILIES picker options)
#   - internal/settings/settings.go    (fontFamilies allow-list)
#
# To ADD a font: add an "id|Family Name" line below, run this script, then add
# the matching entry to FONT_FAMILIES (store.ts) and fontFamilies (settings.go).
# Every family here is OFL-1.1 or Apache-2.0 licensed (free to redistribute).
set -euo pipefail
cd "$(dirname "$0")/.."

UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
OUT="frontend/src/assets/fonts"
CSS="frontend/src/theme/fonts.css"
mkdir -p "$OUT" "$(dirname "$CSS")"

# id | Google Fonts family name
FONTS=$(cat <<'EOF'
inter|Inter
roboto|Roboto
open-sans|Open Sans
lato|Lato
montserrat|Montserrat
poppins|Poppins
nunito|Nunito
work-sans|Work Sans
dm-sans|DM Sans
manrope|Manrope
rubik|Rubik
libre-franklin|Libre Franklin
jost|Jost
comic-neue|Comic Neue
merriweather|Merriweather
lora|Lora
playfair-display|Playfair Display
libre-baskerville|Libre Baskerville
tinos|Tinos
gelasio|Gelasio
jetbrains-mono|JetBrains Mono
fira-code|Fira Code
ibm-plex-mono|IBM Plex Mono
inconsolata|Inconsolata
cousine|Cousine
EOF
)

fetch_weight () {
  local id="$1" fam="$2" wght="$3"
  local q="${fam// /+}" css url sz
  css=$(curl -fsS -A "$UA" "https://fonts.googleapis.com/css2?family=${q}:wght@${wght}&display=swap")
  # Isolate the exact "/* latin */" block (BSD awk has no 3-arg match), grab its woff2 URL.
  url=$(printf '%s\n' "$css" \
    | awk '/\/\* latin \*\//{f=1;next} /\/\* /{f=0} f' \
    | grep -oE 'https://[^)]+\.woff2' | head -1)
  if [ -z "$url" ]; then echo "  MISS w$wght for $fam"; return 1; fi
  curl -fsS -o "$OUT/${id}-${wght}.woff2" "$url"
  sz=$(stat -f%z "$OUT/${id}-${wght}.woff2" 2>/dev/null || stat -c%s "$OUT/${id}-${wght}.woff2")
  echo "  ok w$wght -> ${id}-${wght}.woff2 (${sz} bytes)"
}

while IFS='|' read -r id fam; do
  [ -z "$id" ] && continue
  echo "== $fam ($id) =="
  fetch_weight "$id" "$fam" 400
  fetch_weight "$id" "$fam" 700
done <<< "$FONTS"

# --- regenerate fonts.css from whatever .woff2 files were downloaded ---------
{
  echo "/* Generated by scripts/fetch-fonts.sh — do not edit by hand."
  echo "   One @font-face per bundled Google Fonts file (latin subset, weights 400 & 700)."
  echo "   Imported from frontend/src/main.ts. */"
  while IFS='|' read -r id fam; do
    [ -z "$id" ] && continue
    for w in 400 700; do
      [ -f "$OUT/${id}-${w}.woff2" ] || continue
      printf '@font-face{font-family:%s;font-style:normal;font-weight:%s;font-display:swap;src:url("../assets/fonts/%s-%s.woff2") format("woff2");}\n' \
        "'$fam'" "$w" "$id" "$w"
    done
  done <<< "$FONTS"
} > "$CSS"

echo "=== done: $(ls "$OUT"/*.woff2 2>/dev/null | wc -l | tr -d ' ') files, $(du -sh "$OUT" | cut -f1) total ==="
echo "=== wrote $CSS ==="
