// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {settings} from '../models';
import {notes} from '../models';

export function AddAllowlistEntry(arg1:string):Promise<Array<string>>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ConsumePendingFile():Promise<string>;

export function GetAPIFingerprint():Promise<string>;

export function GetAPIKey():Promise<string>;

export function GetAPIStatus():Promise<main.APIStatus>;

export function GetAPIURL():Promise<string>;

export function GetAllowlist():Promise<Array<string>>;

export function GetSettings():Promise<settings.Settings>;

export function GetUpdateInfo():Promise<main.UpdateInfo>;

export function GetVersion():Promise<string>;

export function InstallUpdate():Promise<void>;

export function InstallerChooseDir():Promise<string>;

export function InstallerFinish(arg1:boolean,arg2:boolean,arg3:boolean):Promise<string>;

export function InstallerInstall():Promise<string>;

export function InstallerState():Promise<main.InstallerState>;

export function InstallerUninstall():Promise<string>;

export function LoadSession():Promise<string>;

export function OpenFile():Promise<main.FileResult>;

export function OpenPath(arg1:string):Promise<main.FileResult>;

export function RemindUpdateLater():Promise<void>;

export function RemoveAllowlistEntry(arg1:string):Promise<Array<string>>;

export function RotateAPIKey():Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string,arg2:string):Promise<main.FileResult>;

export function SaveSession(arg1:string):Promise<void>;

export function SetAPIAutoStart(arg1:boolean):Promise<void>;

export function SetFontFamily(arg1:string):Promise<void>;

export function SetFontSize(arg1:number):Promise<void>;

export function SetHTTPS(arg1:boolean):Promise<main.APIStatus>;

export function SetOpacity(arg1:number):Promise<void>;

export function SetTabPosition(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUpdateAutoCheck(arg1:boolean):Promise<void>;

export function SetWordWrap(arg1:boolean):Promise<void>;

export function ShuffleAPIPort():Promise<main.APIStatus>;

export function SkipUpdateVersion():Promise<void>;

export function StartAPIServer():Promise<main.APIStatus>;

export function Stats(arg1:string):Promise<notes.Stats>;

export function StopAPIServer():Promise<main.APIStatus>;

export function UIAck(arg1:string,arg2:string):Promise<void>;
