// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowlistEntry(arg1) {
  return window['go']['main']['App']['AddAllowlistEntry'](arg1);
}

export function ConsumePendingFile() {
  return window['go']['main']['App']['ConsumePendingFile']();
}

export function GetAPIFingerprint() {
  return window['go']['main']['App']['GetAPIFingerprint']();
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetAPIStatus() {
  return window['go']['main']['App']['GetAPIStatus']();
}

export function GetAPIURL() {
  return window['go']['main']['App']['GetAPIURL']();
}

export function GetAllowlist() {
  return window['go']['main']['App']['GetAllowlist']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function RemoveAllowlistEntry(arg1) {
  return window['go']['main']['App']['RemoveAllowlistEntry'](arg1);
}

export function RotateAPIKey() {
  return window['go']['main']['App']['RotateAPIKey']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SetAPIAutoStart(arg1) {
  return window['go']['main']['App']['SetAPIAutoStart'](arg1);
}

export function SetFontFamily(arg1) {
  return window['go']['main']['App']['SetFontFamily'](arg1);
}

export function SetFontSize(arg1) {
  return window['go']['main']['App']['SetFontSize'](arg1);
}

export function SetHTTPS(arg1) {
  return window['go']['main']['App']['SetHTTPS'](arg1);
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}

export function SetTabPosition(arg1) {
  return window['go']['main']['App']['SetTabPosition'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWordWrap(arg1) {
  return window['go']['main']['App']['SetWordWrap'](arg1);
}

export function ShuffleAPIPort() {
  return window['go']['main']['App']['ShuffleAPIPort']();
}

export function StartAPIServer() {
  return window['go']['main']['App']['StartAPIServer']();
}

export function Stats(arg1) {
  return window['go']['main']['App']['Stats'](arg1);
}

export function StopAPIServer() {
  return window['go']['main']['App']['StopAPIServer']();
}

export function UIAck(arg1, arg2) {
  return window['go']['main']['App']['UIAck'](arg1, arg2);
}
